POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Yamit",
  "email": "yamit@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Yamit",
  "email": "yamit@example.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yamit@example.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Dana",
  "email": "dana@gmail.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Noam",
  "email": "noam@gmail.com",
  "password": "123456"
}